server:
  port: 8090
spring:
  datasource:
    hikari:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/merryaround?characterEncoding=utf8&serverTimezone=UTC
      username: test
      password: test
      type: com.zaxxer.hikari.HikariDataSource
      connectionTimeout: 5000
      maximumPoolSize: 100
      minimumIdle: 10
      idleTimeout: 600000
      maxLifetime: 1800000
      poolName: merryaround